export type HIDE = 'hide';
export const HIDE: HIDE = 'hide';
export type SHOW = 'show';
export const SHOW: SHOW = 'show';

export type INIT_APP = 'INIT_APP';
export const INIT_APP: INIT_APP = 'INIT_APP';

export type GRID_SETTINGS = 'GRID_SETTINGS';
export const GRID_SETTINGS: GRID_SETTINGS = 'GRID_SETTINGS';
export type COLUMN_COUNT = 'COLUMN_COUNT';
export const COLUMN_COUNT: COLUMN_COUNT = 'COLUMN_COUNT';
export type ROW_COUNT = 'ROW_COUNT';
export const ROW_COUNT: ROW_COUNT = 'ROW_COUNT';
export type PIXEL_SIZE = 'PIXEL_SIZE';
export const PIXEL_SIZE: PIXEL_SIZE = 'PIXEL_SIZE';

export type BACKGROUND_COLOR = 'BACKGROUND_COLOR';
export const BACKGROUND_COLOR: BACKGROUND_COLOR = 'BACKGROUND_COLOR';
export type BACKGROUND_RGB_COLOR = 'BACKGROUND_RGB_COLOR';
export const BACKGROUND_RGB_COLOR: BACKGROUND_RGB_COLOR = 'BACKGROUND_RGB_COLOR';
export type PIXEL_COLOR = 'PIXEL_COLOR';
export const PIXEL_COLOR: PIXEL_COLOR = 'PIXEL_COLOR';
export type CONVERTED_PIXEL_RGB_COLOR = 'CONVERTED_PIXEL_RGB_COLOR';
export const CONVERTED_PIXEL_RGB_COLOR: CONVERTED_PIXEL_RGB_COLOR = 'CONVERTED_PIXEL_RGB_COLOR';
export type PIXEL_RGB_COLOR = 'PIXEL_RGB_COLOR';
export const PIXEL_RGB_COLOR: PIXEL_RGB_COLOR = 'PIXEL_RGB_COLOR';
